src/objects/PDF__c.object
<CustomObject>
    <description>The master record for a pdf object. Used to take pdfs and turn them into vf pages. PDF records should be linked to/named after its corresponding vf page.</description>
    <fields>
        <fullName>VFPageId__c</fullName>
        <description>The Id of the VFPage Linked To The PDF.</description>
        <inlineHelpText>The Id of the VFPage Linked To The PDF.</inlineHelpText>
        <label>VFPageId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>PDF</label>
    <nameField>
        <label>PDF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PDFs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PDFPage__c.object
<CustomObject>
    <description>These are the pages associated to a pdf object</description>
    <fields>
        <fullName>Image_URL__c</fullName>
        <description>The URL of the image for the page</description>
        <inlineHelpText>The URL of the image for the page</inlineHelpText>
        <label>Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>PDF__c</fullName>
        <description>The pdf record related to the page</description>
        <label>PDF</label>
        <referenceTo>PDF__c</referenceTo>
        <relationshipLabel>PDFPages</relationshipLabel>
        <relationshipName>PDFPages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Page_Number__c</fullName>
        <description>The order this page will be in the generated pdf</description>
        <inlineHelpText>What page is this in the pdf?</inlineHelpText>
        <label>Page Number</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PDFPage</label>
    <nameField>
        <label>PDFPage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PDFPages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PDFtoVFGenerator_Test.cls
@isTest
public class PDFtoVFGenerator_Test 
{
	public static testmethod void testGeneration()
    {
        /*PDF__c pdf = new PDF__c(name='TestyBoi',  VFPageId__c='123456789987654321');
        insert pdf;
        
        PDFPage__c pdfPage = new PDFPage__c(name='TestyBoiPage', PDF__c = pdf.id, Page_Number__c = 1);
        insert pdfPage;
        
        PDFPageElement__c pdfPageElement = new PDFPageElement__c(name='TestyBoiElement', 
                                                                 PDFPage__c = pdfPage.id, 
                                                                 Image_URL__c='www.google.com');
        insert pdfPageElement;
        Test.setMock(HttpCalloutMock.class, new PDFtoVFGeneratorMockHTTP_Test());
		PDFtoVFGenerator.VFToolingManager(pdf.id);*/
    }
}